server:
  port: 8100

spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tmbm?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: sa
    password:
    sql:
      init:
        schema-locations: classpath:schema.sql
  data:
    redis:
      port: 6379
      host: localhost

