server:
  port: 8100

spring:
  config:
    activate:
      on-profile: local
  application:
    name: tmbm-backend-local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:tmbm
    username: sa
    password:
